# Generated by Django 3.1.2 on 2021-07-16 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='Disability',
            field=models.TextField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
