# Generated by Django 3.1.2 on 2021-07-16 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacc', '0002_details_disability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='Aadhar_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='details',
            name='Disability',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='details',
            name='Dose',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='details',
            name='Name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='details',
            name='Vaccine',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name='details',
            table='vacc_details',
        ),
    ]
