# Generated by Django 3.1.2 on 2021-07-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacc', '0004_auto_20210716_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='District',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='Ref_token',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='State',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
