# Generated by Django 3.1.2 on 2021-07-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacc', '0005_auto_20210716_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='Aadress',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='details',
            name='Group',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='details',
            name='Pin',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
